### ISSUE TITLE
Out Of Date

### ISSUE THREAD

**Issue by barrymichaeldoyle** [foisonocean/protoc-gen-grpc-web-npm#1]
Hey this tool is really wonderful, unfortunately there are some bugs that newer versions of the official tool resolve. Could you update the tool?

**Comment by foisonocean** [comment]
Fixed

**Comment by jsmouret** [comment]
1.1.0 is out :)
thanks a lot!

**Comment by foisonocean** [comment]
@jsmouret 
fixed in ce12c72b94fc3ea029ef926589bdab387835faed
